baseURL = 'https://acidpizza.github.io/technical-learning'
languageCode = 'en-us'
title = 'Technical Learning'
theme = "docsy"

[markup]
  [markup.highlight]
    # https://xyproto.github.io/splash/docs/longer/all.html
    style = 'vs'

[markup.goldmark]
  [markup.goldmark.renderer]
  # Allow multiline in tables with <br>
  unsafe = true 

# Enable syntax highlighting and copy buttons on code blocks with Prism
# prism_syntax_highlighting = true